homeassistant:
  name: Casa De Winters
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: 192
  unit_system: imperial
  time_zone: America/Chicago
  customize: !include_dir_merge_named customize
  packages: !include_dir_named packages


frontend:

config:

http:
  api_password: !secret api_password
  base_url: hass.bwinters.net:8123

updater:
  include_used_components: true

discovery:
conversation:
history:
logbook:
sun:
ios:

# Weather prediction
#sensor:
#  - platform: yr

# Text to speech
tts:
  - platform: google
    language: 'en'
  #- platform: amazon_polly
  #  aws_access_key_id: !secret polly_access_key_id
  #  aws_secret_access_key: !secret polly_secret_key
  #  profile_name: !secret polly_profile_name
  #  region_name: 'us-east-1'

camera:
  - platform: synology
    url: !secret synology_url
    username: !secret synology_username
    password: !secret synology_password
    timeout: 15
    verify_ssl: False

zwave:
  usb_path: /dev/ttyACM0
  network_key: "0xE6, 0xC3, 0x1E, 0xA7, 0xBC, 0xA2, 0xD4, 0x3D, 0x93, 0x0E, 0xB4, 0x80, 0x37, 0x59, 0x4D, 0xFC"

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret

netatmo:
  api_key: !secret netatmo_api_key
  secret_key: !secret netatmo_secret_key
  username: !secret netatmo_username
  password: !secret netatmo_password
  discovery: true

cover:
  - platform: myq
    username: !secret myq_username
    password: !secret myq_password
    type: chamberlain

panel_custom:
  - name: floorplan
    sidebar_title: Floorplan
    sidebar_icon: mdi:home
    url_path: floorplan
    config: !include floorplan.yaml

group: !include_dir_merge_named group
device_tracker: !include_dir_merge_list device_tracker
sensor: !include_dir_merge_list sensor
automation: !include_dir_merge_list automation
scene: !include_dir_merge_list scene
switch: !include_dir_merge_list switch
script: !include_dir_merge_named script
#input_boolean: !include_dir_merge_named input_boolean
shell_command: !include_dir_merge_named shell_command
